services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: seaus-app:latest
    container_name: seaus-app-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules

